### ISSUE TITLE
Check release notes on Fabric.io

### ISSUE THREAD

**Issue by magyarosibotond** [halcyonmobile/ReleaseRadar#9]
Add ability to check release notes on Fabric. 
In many cases, beta distribution happens through [Fabric.io](fabric.io).
A new data source is needed to support this kind of distribution.

Not sure if it's possible though. I've been looking for a public API we can use, but they don't really advertise it.

**Comment by zierka** [comment]
I'm not aware of an API either. Also please note that Fabric is being integrated into Firebase (https://get.fabric.io/roadmap). IMO I wouldn't call this a "must-have" feature for v1.

**Comment by magyarosibotond** [comment]
It wasn't part of the **MVP Milestone** just the Project board.

Closing this issue now.
